extends SceneTree
const State = preload("res://scripts/ecology.gd")
const Study = preload("res://scripts/mystery.gd")
var failures := 0
var checks := 0
func check(condition: bool, message: String) -> void:
	checks += 1
	if not condition:
		push_error(message)
		failures += 1
func prepared():
	var s = State.new()
	s.document("ant")
	s.mystery.discover_trail(s.day,s.hour)
	s.mystery.inspect_patch(0,s.day,s.hour)
	s.mystery.inspect_patch(1,s.day,s.hour)
	return s
func roundtrip(s, label: String) -> void:
	var path := "user://mystery-test-"+label+".json"
	check(s.save_game(path)==OK,"Save "+label)
	var restored = State.new()
	check(restored.load_game(path),"Load "+label)
	check(restored.mystery.phase==s.mystery.phase,"Phase retained "+label)
	check(restored.documented==s.documented,"Species retained "+label)
	check(is_equal_approx(float(restored.mystery.water[1]),float(s.mystery.water[1])),"Patch state retained "+label)
	check(restored.mystery.notes==s.mystery.notes,"Evidence retained "+label)
	DirAccess.remove_absolute(path)
func _init() -> void:
	var empty = State.new()
	empty.mystery.begin_baseline(1,9)
	check(empty.mystery.phase=="discovery","Cannot begin without observations")
	empty.mystery.record_plate(1,9)
	check(empty.mystery.plate_record.is_empty(),"Cannot award a plate before evidence")
	var s = prepared()
	check(s.unlocked==1 and not s.zone_open(1),"Study does not bypass sense spine")
	s.mystery.predict("Shelter may make no difference.",s.day,s.hour)
	s.mystery.begin_baseline(s.day,s.hour)
	check(s.mystery.water==[82.0,82.0],"Matched initial wetness")
	s.advance_hours(1.25)
	check(s.mystery.baseline.samples.size()==2,"Partial interval records whole observation boundaries")
	roundtrip(s,"baseline-running")
	s.advance_hours(2.75)
	check(s.mystery.phase=="baseline_ready","Baseline completes")
	check(s.mystery.baseline.samples.size()==5,"All five samples retained")
	check(is_equal_approx(s.mystery.water[0],57.2) and is_equal_approx(s.mystery.water[1],34.8),"Distinct rates emerge from local shelter")
	check(not s.mystery.conclusion().contains("supports a role"),"Baseline alone does not claim causation")
	s.mystery.encourage_shelter(s.day,s.hour)
	check(s.mystery.phase=="baseline_ready","Require comparison before intervention")
	s.mystery.review()
	s.mystery.encourage_shelter(s.day,s.hour)
	var a_shelter: float = s.mystery.shelter[0]
	var initial_habitat = s.habitats.duplicate(true)
	s.advance_hours(3)
	check(s.mystery.phase=="growing" and s.mystery.shelter[1]==0.22,"Growth takes time")
	roundtrip(s,"growth")
	s.advance_hours(5)
	check(s.mystery.phase=="ready_trial","Growth finishes after eight model hours")
	check(s.mystery.shelter[0]==a_shelter,"A's shelter remains unchanged")
	check(s.habitats==initial_habitat,"Local shelter does not mutate whole-zone habitat")
	roundtrip(s,"ready-trial")
	s.mystery.begin_trial(s.day,s.hour)
	s.zone=1
	s.advance_day()
	check(s.mystery.phase=="result","Skipped day completes an off-screen trial")
	check(s.mystery.trial.samples.size()==5,"Skipping saves all intermediate evidence")
	check(is_equal_approx(s.mystery.water[0],57.2) and is_equal_approx(s.mystery.water[1],57.2),"Only B's outcome changes")
	check(s.mystery.baseline.samples[-1].water[1]<s.mystery.trial.samples[-1].water[1],"Before evidence was not overwritten")
	roundtrip(s,"result")
	s.mystery.review()
	s.mystery.reflect("I would revise my prediction.",s.day,s.hour)
	s.mystery.record_plate(s.day,s.hour)
	check(not s.mystery.plate_record.is_empty(),"An incorrect prediction does not block reward")
	check(s.mystery.plate_record.prediction=="Shelter may make no difference.","Original prediction preserved")
	check(s.documented==["ant"] and s.unlocked==1,"Relationship remains separate from species and progression")
	var plate_before = s.mystery.plate_record.duplicate(true)
	s.mystery.record_plate(s.day+1,s.hour)
	check(s.mystery.plate_record==plate_before,"Recording is idempotent")
	roundtrip(s,"earned-plate")
	check(s.mystery.repeat_study(s.day,s.hour),"Can repeat without resetting habitat")
	check(s.mystery.archive.size()==1 and s.mystery.plate_record==plate_before,"Repeat preserves history and earned plate")
	check(s.mystery.shelter[1]==0.78,"Repeat retains changed shelter")
	roundtrip(s,"repeat")
	var no_prediction = prepared()
	no_prediction.mystery.begin_baseline(1,9)
	no_prediction.advance_hours(4)
	no_prediction.mystery.review()
	no_prediction.mystery.encourage_shelter(1,13)
	no_prediction.advance_hours(8)
	no_prediction.mystery.begin_trial(1,21)
	no_prediction.advance_hours(4)
	check(no_prediction.day==2 and is_equal_approx(no_prediction.hour,1),"Within-day clock crosses midnight correctly")
	check(not no_prediction.events.is_empty(),"Completion notice survives crossing midnight")
	no_prediction.mystery.review()
	no_prediction.mystery.record_plate(2,1)
	check(not no_prediction.mystery.plate_record.is_empty(),"No prediction or reflection is required")
	# Tiny frame increments and one large skip must produce the same recorded series.
	var split = prepared()
	split.mystery.begin_baseline(1,9)
	for i in range(401): split.mystery.advance(0.01)
	check(split.mystery.baseline.samples==no_prediction.mystery.baseline.samples,"Frame-rate independent evidence")
	# v1 migration must preserve the old save and all species progress.
	var path := "user://mystery-migration-test.json"
	var legacy = prepared()
	legacy.save_game(path)
	var d = JSON.parse_string(FileAccess.get_file_as_string(path))
	d.version=1
	d.erase("mystery")
	var file := FileAccess.open(path,FileAccess.WRITE)
	file.store_string(JSON.stringify(d))
	file.close()
	var migrated = State.new()
	check(migrated.load_game(path),"v1 save migrates")
	check(migrated.documented==["ant"] and migrated.unlocked==1,"Migration retains discoveries")
	check(FileAccess.file_exists(path+".v1-backup"),"Migration preserves original file")
	check(migrated.mystery.phase=="discovery","Existing forest gets the new optional mystery")
	migrated.save_game(path)
	check(JSON.parse_string(FileAccess.get_file_as_string(path)).version==State.SAVE_VERSION,"Next save writes current schema")
	DirAccess.remove_absolute(path)
	DirAccess.remove_absolute(path+".v1-backup")
	var broken: Dictionary = s.mystery.serialize().duplicate(true)
	broken.baseline.samples=[]
	var invalid = Study.new()
	check(not invalid.restore(broken),"Reject malformed evidence before committing loaded state")
	var other_seed = prepared()
	other_seed.seed_value=234
	other_seed.mystery.begin_baseline(1,9)
	other_seed.advance_hours(4)
	check(other_seed.mystery.baseline.samples==split.mystery.baseline.samples,"Seed cannot change authored scientific relationship")
	print("Mystery checks: ",checks,"; failures: ",failures)
	quit(failures)
